/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package custom;

import db.ContactDB;
import java.awt.Container;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import main.EditContact;
import main.Home;


/**
 *
 * @author microsoftm
 */
public class ContactPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContactPanel
     * @param contact
     * @param parent
     */
    public ContactPanel(Contact contact, Container parent) {
        initComponents();
        this.contact = contact;
        this.parent = parent;
//        this.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
        addData(contact);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactSeperator = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        phones = new javax.swing.JList<>();
        lblName = new javax.swing.JLabel();
        lblDelete = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(204, 204, 204));
        setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 100));

        contactSeperator.setBackground(new java.awt.Color(204, 204, 204));

        phones.setBackground(new java.awt.Color(51, 51, 51));
        phones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        phones.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        phones.setForeground(new java.awt.Color(204, 204, 204));
        phones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        phones.setToolTipText("");
        jScrollPane1.setViewportView(phones);

        lblName.setBackground(new java.awt.Color(51, 51, 51));
        lblName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 204, 204));
        lblName.setText("jLabel1");

        lblDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash-9-24.png"))); // NOI18N
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteMouseClicked(evt);
            }
        });

        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-24.png"))); // NOI18N
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(contactSeperator)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDelete)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseClicked
        // TODO add your handling code here:
        String name = contact.getName();
        int result = JOptionPane.showConfirmDialog(null,"Sure? You want to delete?", "Warning",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
        
        if(result == JOptionPane.YES_OPTION){
            System.out.println("DELETE " + contact.getContactId());
            ContactDB cdb = new ContactDB();
            try {
                cdb.deleteContact(contact);
                JOptionPane.showMessageDialog(null, ""+ name +" was deleted Successfully");
                new Home().setVisible(true);
                this.parent.setVisible(false);            
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else if(result == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, ""+ name + " was not deleted");
        }
        
    }//GEN-LAST:event_lblDeleteMouseClicked

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        // TODO add your handling code here:
        System.out.println("UPDATE " + contact.getContactId());
        new EditContact(this.parent, contact).setVisible(true);
        this.parent.setVisible(false);            
        
    }//GEN-LAST:event_lblEditMouseClicked

    private void addData(Contact c) {
        lblName.setText(c.getName());
        DefaultListModel dlm = new DefaultListModel();
        c.getPhone().forEach((phone) -> {
            dlm.addElement(phone);
        });
        phones.setModel(dlm);
    }

    // vars
    private final Contact contact;
    private final Container parent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator contactSeperator;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblName;
    private javax.swing.JList<String> phones;
    // End of variables declaration//GEN-END:variables
}
